import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('dataset.csv')
cols=df.columns
rows=df.shape[0]
print("Number of customers: ",rows)
print("Number of features: ",len(cols))
print("Numerical features: ",df.select_dtypes(include='number').columns)
print("Categorical features: \n",df.select_dtypes(include='object').columns)
print(df['PaymentMethod'].unique())
print(df['Contract'].unique())
print(df['InternetService'].unique())
print("Missing values counts: ",df.isnull().sum())
print("Missing values percentage: ",df.isnull().mean()*100)
print("Duplicate rows count: ",df.duplicated().sum())
print("Duplicate Customer IDs count: ",df['customerID'].duplicated().sum())
temp=pd.to_numeric(df['TotalCharges'], errors='coerce')
print("Inconsistent format value count: ",temp.isna().sum())
print(df['PaymentMethod'].unique())
print(df['TechSupport'].unique())
print(df['customerID'].unique())
df=df.drop('customerID', axis=1)
df['TotalCharges']=pd.to_numeric(df['TotalCharges'], errors='coerce')
df['TotalCharges'] =df['TotalCharges'].fillna(df['TotalCharges'].mean())  
print(df)
df['Churn'].value_counts().plot(kind="bar")
plt.figure(figsize=(10, 6))   
df['PaymentMethod'].value_counts().plot(kind="bar")
plt.tight_layout()
plt.figure(figsize=(10, 6))   
df['TotalCharges'].plot(kind='hist', bins=30, edgecolor='black')
plt.tight_layout()
plt.figure(figsize=(10, 6))   
df['MonthlyCharges'].plot(kind='hist', bins=30, edgecolor='black')  
plt.tight_layout()
# plt.show()
print("Number of Churned vs Non Churned: ")
print(df['Churn'].value_counts())
print("Percentage of Churned vs Non Churned: ")
print(df['Churn'].value_counts(normalize=True)*100)
churn_by_contract=(pd.crosstab(df['Contract'],df['Churn'],normalize='index')*100).round(2)
print(churn_by_contract)
churn_by_contract.plot(kind='bar')
plt.tight_layout()
churn_by_internet=(pd.crosstab(df['InternetService'],df['Churn'],normalize='index')*100).round(2)
print(churn_by_internet)
churn_by_internet.plot(kind='bar')
plt.tight_layout()
# plt.show()
# Tenure vs Churn
plt.figure(figsize=(7,5))
sns.boxplot(x='Churn', y='tenure', data=df)
plt.title('Tenure Distribution by Churn Status')
plt.xlabel('Churn')
plt.ylabel('Tenure (months)')
# plt.show()

# MonthlyCharges vs Churn
plt.figure(figsize=(7,5))
sns.boxplot(x='Churn', y='MonthlyCharges', data=df)
plt.title('Monthly Charges Distribution by Churn Status')
plt.xlabel('Churn')
plt.ylabel('Monthly Charges ($)')
# plt.show()
corr_matrix=df.corr(numeric_only=True)
print(corr_matrix)
sns.heatmap(corr_matrix, annot=True)
plt.title('Correlation Matrix of Numerical Features')
plt.tight_layout()
plt.show()
clean_df=df.copy()
clean_df.to_csv('clean_churn.csv', index=False)
print(clean_df.info())
